# Generated by Django 4.2.2 on 2023-07-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniojobsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_add',
            field=models.CharField(default='address here', max_length=20),
        ),
    ]
