# Generated by Django 4.2.2 on 2023-06-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geniojobsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='title',
            new_name='name',
        ),
    ]
