# Generated by Django 4.2.2 on 2023-06-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geniojobsapp', '0002_rename_title_data_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
    ]
