# Generated by Django 4.2.2 on 2023-06-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniojobsapp', '0003_remove_data_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
