# Generated by Django 4.2.2 on 2023-07-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geniojobsapp', '0003_remove_student_stud_add_student_is_current_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_current',
            new_name='iscurrent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stud_add1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stud_add2',
        ),
    ]
