# Generated by Django 4.2.2 on 2023-07-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniojobsapp', '0004_rename_is_current_student_iscurrent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenioUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('is_employer', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('organization_name', models.CharField(max_length=100)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
