# Generated by Django 4.2.2 on 2023-07-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geniojobsapp', '0005_geniousers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geniousers',
            name='organization_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
