# Generated by Django 4.2.2 on 2023-07-14 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geniojobsapp', '0008_job_listing_genio_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Seeker_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=200)),
                ('resume', models.FileField(max_length=254, upload_to=None)),
                ('cover_letter', models.TextField()),
                ('education', models.CharField(default='', max_length=100)),
                ('percentage', models.FloatField(default=0)),
                ('total_experience', models.IntegerField(default=0)),
                ('genio_user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='geniojobsapp.geniousers')),
            ],
        ),
    ]
