# Generated by Django 4.2.2 on 2023-07-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geniojobsapp', '0009_job_seeker_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker_profile',
            name='genio_user_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='geniojobsapp.geniousers'),
        ),
    ]
