# Generated by Django 4.2.2 on 2023-08-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geniojobsapp', '0011_alter_job_seeker_profile_cover_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='applied_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pending', models.BooleanField(default='False')),
                ('is_rejected', models.BooleanField(default='False')),
                ('job_listing_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='geniojobsapp.job_listing')),
                ('job_seeker_profile_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='geniojobsapp.job_seeker_profile')),
            ],
        ),
    ]
