# Generated by Django 4.2.2 on 2023-08-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geniojobsapp', '0012_applied_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_jobs',
            name='genio_user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='geniojobsapp.geniousers'),
        ),
    ]
