# Generated by Django 4.2.2 on 2023-08-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geniojobsapp', '0013_applied_jobs_genio_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applied_jobs',
            name='genio_user_id',
        ),
    ]
